### PR TITLE
feat: add ctrl delete to forward delete word

### LINKED ISSUE #124: feat: ctrl delete to delete a word
i keep using this in my text editor would be nice in shell

### PR DESCRIPTION
**Pull request by sammy-ette**
closes #124
@Renzix test thanks

---
- [x] I have reviewed CONTRIBUTING.md.
- [x] My commits and title use the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [ ] I have documented any breaking changes according to [SemVer](https://semver.org/).
---

### CODE REVIEW

**Comment by Renzix** [comment]
Works fine in st, alacritty, xfce4-terminal, kitty and xterm. Doesnt work in st but st is dumb. I dont know how accurate you want to be but Ctrl Delete in bash does this 
`this |is a test` -> `this  _a test` // |i means the block is on i
but current implementation does this
`this |is a test` -> `this |a test`  // the cursor block is ontop of a
basically in vim terms ctrl delete is de while currently its dw (but vim actually is dumb and assumes dw is de which is ??? and wrong)
		rl.saveToRegister(rl.viJumpE(tokeniseLine)+1)
		rl.viDeleteByAdjust(rl.viJumpE(tokeniseLine)+1)
would be correct
image
vs 
image

**Comment by Renzix** [comment]
looks like C-DEL is the same as M-d which goes till M-f (forward-word)

**Comment by Renzix** [comment]
dunno if you are already done but

```golang
func (rl *Instance) emacsForwardWord(tokeniser tokeniser) (adjust int) {
	split, index, pos := tokeniser(rl.line, rl.pos)
	if len(split) == 0 {
		return
	}

	word := rTrimWhiteSpace(split[index])

	switch {
	case len(split) == 0:
		return
	case index == len(split)-1 && pos >= len(word)-1:
		return
	case pos >= len(word)-1:
		word = rTrimWhiteSpace(split[index+1])
		adjust = len(split[index]) - pos
		adjust += len(word)
	default:
		adjust = len(word) - pos
	}
	return
}
```

also would double as M-f

**Comment by TorchedSammy** [comment]
done - can you check what ctrl delete is on st? gotta be inclusive ~~even though i agree st is dumb~~

**Comment by Renzix** [comment]
image
so 27 91 77 4

**Comment by Renzix** [comment]
btw im actually really dumb, can make this 
image
	case pos >= len(word):
and it should work and still actually delete the last char

**Pull request merged**
