### PR TITLE
feat: case insensitive tab completion

### LINKED ISSUE #104: feat: case insensitive (file) completion
personally i need this as well and i'm sure other people would, could probably be a configurable option

### PR DESCRIPTION
**Pull request by sammy-ette**
closes #104 

adds case insensitive tab completion. this is both for binaries and files.
this will be configurable via `hilbish.tabInsensitive`

### CODE REVIEW

**Comment by TorchedSammy** [comment]
currently it's broken if a user tries to complete with a 1 character prefix

**Comment by TorchedSammy** [comment]
i dont know why that happens and i cant be bothered anymore

**Comment by sonphantrung** [comment]
<a href="https://ibb.co/20r1WYD">image</a>
Is this the error that you're referencing?

**Comment by TorchedSammy** [comment]
oh that seems to be another issue nice
what I was talking about is that it wouldn't complete properly and still include the prefix and act weird, not outright panic

**Pull request closed without merging**
