### PR TITLE
fix: naming a alias command with the command name inside of alias

### PR DESCRIPTION
**Pull request by ratogabriel**
The for loop used to extract command and add args dosen't work when the
alias has the same name as the comand itself, beside it I saw no reason
to keep using a for loop to extrac args

---
- [x] I have reviewed CONTRIBUTING.md.
- [x] My commits and title use the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [ ] I have documented any breaking changes according to [SemVer](https://semver.org/).
---

### CODE REVIEW

**Comment by TorchedSammy** [comment]
the for loop is for an alias of an alias, this is basically just reverting what i did for it to do that

**Comment by ratogabriel** [comment]
> the for loop is for an alias of an alias, this is basically just reverting what i did for it to do that

Ok... I can do it other way around

**Comment by TorchedSammy** [comment]
well we dont want to block it, its why the for loop is there in the first place
so instead of doing that, after checking and replacing the alias u can just check if the alias name and the command that is aliased is the same. if so, break the loop (only do this *after* expanding though*)
so if you do that, can u git reset then force push to remove the other commits?

**Comment by ratogabriel** [comment]
I think this is it, did what you proposed and worked

**Pull request merged**
