### PR TITLE
feat: add .editorconfig file

### PR DESCRIPTION
**Pull request by danitw**
---
- [X] I have reviewed CONTRIBUTING.md.
- [X] My commits and title use the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [ ] I have documented changes and additions in the CHANGELOG.md.
---
(I was in doubt whether to use chore or feat))

I added a .editorconfig because I think it makes it easier for people who use editors that support this tool

### CODE REVIEW

**Comment by TorchedSammy** [comment]
can you force the indent style to be tabs specifically?

**Comment by TorchedSammy** [comment]
> (I was in doubt whether to use chore or feat))

it should be chore

**Comment by danitw** [comment]
> can you force the indent style to be tabs specifically?

yes, I did not put it because the CONTRIBUTING.md had not specified

**Comment by danitw** [comment]
I can't do the rebase, strange

**Comment by danitw** [comment]
Got it!

**Review by TorchedSammy — APPROVED** [review]

**Pull request merged**
