### PR TITLE
feat: lua backed history

### LINKED ISSUE #181: feat: lua backed history
if the shell history is entirely lua backed, this means it will be able to completely control history input and how/when it's added, and hilbish will also use it to retrieve the history (in the case of the ctrl r menu)

features to come out of this:
- alternate history storage/backends (json? yaml? an actual database?)
- lua side chooses if history is added for all command input
- gateway for future features relating to the history menu (better and custom sort/filter)

### PR DESCRIPTION
**Pull request by sammy-ette**
closes #181

---
- [x] I have reviewed CONTRIBUTING.md.
- [x] My commits and title use the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [x] I have documented changes and additions in the CHANGELOG.md.
---

### CODE REVIEW

**Comment by Renzix** [comment]
I get this when I try to run changes

```
Missing nature module, some functionality and builtins will be missing.
local error: open nature/init.lua: no such file or directory
global install error: error: /usr/share/hilbish/nature/init.lua:13: could not find package 'nature.history'
```

it should be
```lua
require 'nature.opts.history'
```
i think (that fixes it)

**Comment by Renzix** [comment]
Also it may be useful expose the dump function in the lua history module (for people who want 0 history forever) because this just doesnt save future history (unless it does)

**Comment by TorchedSammy** [comment]
aaaaa conflicts

that should just be removed since the opts will handle it

**Comment by Renzix** [comment]
Yup works without

**Pull request merged**
